#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 92		# Set DPI. User may want to use a larger number for larger screens.
xrandr --setprovideroutputsource modesetting NVIDIA-0					#Enable this for envycontrol Nvidia setup
xrandr --output HDMI-1-1 --mode 1920x1080 --rate 74.97 --set "Broadcast RGB" "Full"    #Enable this for envycontrol Nvidia setup
#xrandr --output HDMI-1 --mode 1920x1080 --rate 74.97 --set "Broadcast RGB" "Full"
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
xrdb ${HOME}/.Xresources	# Uncomment to use Xresources colors/settings on startup
setxkbmap tr	# Sets the locale to TR, necessary for snippets to work

autostart="mpd picomglx dunst unclutter pipewire clipmenud"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
